# Generated by Django 2.0 on 2017-12-07 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_scenario_text_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.IntegerField(default=1)),
                ('link_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Text_Input')),
                ('scenario_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_link', to='polls.Scenario')),
                ('scenario_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_link', to='polls.Scenario')),
            ],
        ),
    ]
