# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ImageScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='imagelink',
            name='image_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_image', to='polls.ImageScenario'),
        ),
        migrations.AddField(
            model_name='imagelink',
            name='image_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_image', to='polls.ImageScenario'),
        ),
    ]
