# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180109_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('end_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_image', to='polls.ImageScenario')),
                ('start_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_image', to='polls.ImageScenario')),
            ],
        ),
    ]
