# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 05:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0006_actionimage_baseimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('base_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.BaseImage')),
                ('last_action_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ActionImage')),
            ],
        ),
        migrations.AddField(
            model_name='authors',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Story'),
        ),
        migrations.AddField(
            model_name='authors',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
